{% set name = "django-silk" %}
{% set version = "5.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4c09b2ff37a45af70553cb04ff507f512abfc768646de13373b9741fe8d538da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - sqlparse
    - autopep8
    - gprof2dot >=2017.09.19

test:
  imports:
    - silk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jazzband/django-silk
  summary: Silky smooth profiling for the Django Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
