{% set name = "django-silk" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-silk-{{ version }}.tar.gz
  sha256: 34abb5852315f0f3303d45b7ab4a2caa9cf670102b614dbb2ac40a5d2d5cbffb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - setuptools-scm
    - pip
  run:
    - python >=3.7,<3.11
    - django >=3.2
    - sqlparse
    - autopep8
    - gprof2dot >=2017.09.19

test:
  imports:
    - silk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-silk
  summary: Silky smooth profiling for the Django Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
