{% set name = "django-silk" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b17fe57e6b4c89ccc8dfc974bf4caf08d7d297c51acf60c71ab8eaad1d0986b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >=3.8
    - django >=4.2
    - sqlparse
    - autopep8
    - gprof2dot >=2017.09.19

test:
  imports:
    - silk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-silk
  summary: Silky smooth profiling for the Django Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
