{% set name = "django-silk" %}
{% set version = "5.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f3b2be63c0b92a660b7aaee591c8a505bb0757e2de55f6914cb95c1ee9ea2138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - sqlparse
    - autopep8
    - gprof2dot >=2017.09.19

test:
  imports:
    - silk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jazzband/django-silk
  summary: Silky smooth profiling for the Django Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
