{% set name = "django-silk" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 39ddeda80469d5495d1cbb53590a9bdd4ce30a7474dc16ac26b6cbc0d9521f50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - sqlparse
    - autopep8
    - gprof2dot >=2017.09.19

test:
  imports:
    - silk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-silk
  summary: Silky smooth profiling for the Django Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
